services:
  traefik:
    image: 'traefik:2.11.0'
    container_name: 'Horia-Reverse-Proxy'
    command:
      - '--providers.docker=true'
      - '--providers.docker.exposedbydefault=false'
      - '--entrypoints.web.address=:80'
    depends_on:
      - backend
      - frontend
    restart: always
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
    networks:
      - internal
  frontend:
    image: ghcr.io/darnasion/horia_frontend
    depends_on:
      - backend
    container_name: 'Horia-Frontend'
    restart: always
    labels:
      # Explicitly tell Traefik to expose this container
      - 'traefik.enable=true'
      # The port the service will respond on (normally traefik auto detects that, but here it doesnt)
      - 'traefik.http.services.frontend.loadbalancer.server.port=8080'
    networks:
      - internal
  backend:
    image: ghcr.io/darnasion/horia_backend
    extends:
      file: docker-compose.config.yml
      service: backend
    depends_on:
      - database
    container_name: 'Horia-Backend'
    restart: always
    labels:
      # Explicitly tell Traefik to expose this container
      - 'traefik.enable=true'
    environment:
      # Hardcoded environment variables, which should not be changed.
      SQUIRE_JDBC_USER: squire
      SQUIRE_DB_URL: jdbc:mysql://database:3306/squire?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true&tinyInt1isBit=false&sessionVariables=sql_mode='STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION'
      SQUIRE_LOG_PATH: ./Squire.log
      SQUIRE_IMAGES_PATH: ./images
      SQUIRE_USE_SSL: false
      SQUIRE_ENV: prod
    volumes:
      - backend_data:/var/lib/app
    networks:
      - internal
  database:
    image: ghcr.io/darnasion/horia_database
    extends:
      file: docker-compose.config.yml
      service: database
    container_name: 'Horia-Database'
    command: --default-authentication-plugin=caching_sha2_password
    restart: always
    hostname: database
    environment:
      # Hardcoded environment variables, which should not be changed.
      MYSQL_RANDOM_ROOT_PASSWORD: true
      MYSQL_DATABASE: squire
      MYSQL_USER: squire
    volumes:
      - db_data:/var/lib/mysql/
    networks:
      - internal
    ports:
      - "3306:3306"
volumes:
  db_data:
    name: Horia-Database-Volume
  backend_data:
    name: Horia-Backend-Volume
networks:
  internal:
    name: Horia-Internal-Network
